[directories]
astetcdir => /config
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => /var/lib/asterisk
astdbdir => /var/lib/asterisk
astkeydir => /var/lib/asterisk
astdatadir => /var/lib/asterisk
astagidir => /var/lib/asterisk/agi-bin
astspooldir => /var/spool/asterisk
astrundir => /var/run/asterisk
astlogdir => /var/log/asterisk

[options]
verbose = 3
debug = 0
alwaysfork = no
nofork = yes
quiet = no
timestamp = yes
execincludes = no
live_dangerously = no
hideconnect = yes
maxcalls = 150
maxload = 0.0
