[general]
static=yes
writeprotect=yes
clearglobalvars=yes

[dialer-outbound]
exten => _+X!,1,Dial(PJSIP/${EXTEN}@outbound-primary,45)
same => n,GotoIf($["${DIALSTATUS}"="CONGESTION"]?secondary)
same => n,GotoIf($["${DIALSTATUS}"="CHANUNAVAIL"]?secondary)
same => n,Hangup()
same => n(secondary),Dial(PJSIP/${EXTEN}@outbound-secondary,45)
same => n,Hangup()

[reject-inbound]
exten => _X!,1,Hangup(21)
exten => _+X!,1,Hangup(21)
exten => s,1,Hangup(21)
exten => i,1,Hangup(21)
exten => h,1,NoOp(Unsolicited channel rejected)
