[general]
static=yes
writeprotect=yes
clearglobalvars=yes

[reject-inbound]
exten => _X!,1,Hangup(21)
exten => _+X!,1,Hangup(21)
exten => s,1,Hangup(21)
exten => i,1,Hangup(21)
exten => h,1,NoOp(Unsolicited channel rejected)
