[general]
static=yes
writeprotect=yes
clearglobalvars=yes

[dialer-outbound]
exten => _+X!,1,Set(PRIMARY_DIAL=${PJSIP_DIAL_CONTACTS(outbound-primary,outbound-primary-aor,${EXTEN})})
same => n,GotoIf($["${PRIMARY_DIAL}"=""]?secondary)
same => n,Dial(${PRIMARY_DIAL},45)
same => n,Set(PRIMARY_KEYS=${HANGUPCAUSE_KEYS()})
same => n,GotoIf($["${PRIMARY_KEYS}"=""]?finish)
same => n,Set(PRIMARY_CHANNEL=${SHIFT(PRIMARY_KEYS)})
same => n,Set(PRIMARY_TECH=${HANGUPCAUSE(${PRIMARY_CHANNEL},tech)})
same => n,GotoIf($[${REGEX("^SIP (429|480|5[0-9][0-9])($| )" ${PRIMARY_TECH})}=1]?secondary:finish)
same => n(secondary),HangupCauseClear()
same => n,Set(SECONDARY_DIAL=${PJSIP_DIAL_CONTACTS(outbound-secondary,outbound-secondary-aor,${EXTEN})})
same => n,GotoIf($["${SECONDARY_DIAL}"=""]?temporary)
same => n,Dial(${SECONDARY_DIAL},45)
same => n,Set(SECONDARY_KEYS=${HANGUPCAUSE_KEYS()})
same => n,GotoIf($["${SECONDARY_KEYS}"=""]?finish)
same => n,Set(SECONDARY_CHANNEL=${SHIFT(SECONDARY_KEYS)})
same => n,Set(SECONDARY_TECH=${HANGUPCAUSE(${SECONDARY_CHANNEL},tech)})
same => n,GotoIf($[${REGEX("^SIP (429|480|5[0-9][0-9])($| )" ${SECONDARY_TECH})}=1]?temporary:finish)
same => n(temporary),Hangup(41)
same => n(finish),Hangup()

[reject-inbound]
exten => _X!,1,Hangup(21)
exten => _+X!,1,Hangup(21)
exten => s,1,Hangup(21)
exten => i,1,Hangup(21)
exten => h,1,NoOp(Unsolicited channel rejected)
