[global]
type=global
user_agent=voice-dialer-asterisk/22.10.1
endpoint_identifier_order=ip,username
keep_alive_interval=90

[system]
type=system
timer_t1=500
timer_b=32000
compact_headers=no
threadpool_initial_size=10
threadpool_auto_increment=10
threadpool_idle_timeout=60
threadpool_max_size=150

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:31100
external_signaling_address=5.196.90.231
external_media_address=5.196.90.231
allow_reload=no
tos=cs3
cos=3

@@TRUNK_BLOCK@@
