apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: voice-dialer
resources:
  - ../../base
configMapGenerator:
  - name: dialer-runtime
    behavior: replace
    envs:
      - inputs/runtime.env
  - name: dialer-network-values
    behavior: replace
    envs:
      - inputs/network.env
secretGenerator:
  - name: dialer-postgres
    behavior: replace
    envs:
      - inputs/postgres.env
  - name: dialer-app-secrets
    behavior: replace
    envs:
      - inputs/app.env
  - name: dialer-ari-secrets
    behavior: replace
    envs:
      - inputs/ari.env
  - name: dialer-trunk-secrets
    behavior: replace
    envs:
      - inputs/trunk.env
