apiVersion: v1
kind: Namespace
metadata:
  name: sip-b2bua
  labels:
    app.kubernetes.io/name: asterisk-b2bua
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
