[modules]
autoload=yes
preload=res_pjproject.so
preload=res_sorcery_config.so
preload=res_pjsip.so
preload=chan_pjsip.so
noload=chan_sip.so
noload=chan_iax2.so
noload=chan_mgcp.so
noload=chan_skinny.so
noload=chan_unistim.so
noload=pbx_spool.so
noload=app_amd.so
noload=app_mixmonitor.so
noload=app_monitor.so
noload=app_dictate.so
noload=app_voicemail.so
noload=app_minivm.so
noload=res_monitor.so
noload=res_snmp.so
noload=res_hep.so
noload=res_hep_pjsip.so
noload=res_hep_rtcp.so
