apiVersion: v1
kind: Service
metadata:
  name: dialer-rtp-31640-31659
  labels:
    app.kubernetes.io/name: dialer-engine
    app.kubernetes.io/component: rtp
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: dialer-engine
  ports:
    - {name: rtp-31640, port: 31640, targetPort: 31640, nodePort: 31640, protocol: UDP}
    - {name: rtp-31641, port: 31641, targetPort: 31641, nodePort: 31641, protocol: UDP}
    - {name: rtp-31642, port: 31642, targetPort: 31642, nodePort: 31642, protocol: UDP}
    - {name: rtp-31643, port: 31643, targetPort: 31643, nodePort: 31643, protocol: UDP}
    - {name: rtp-31644, port: 31644, targetPort: 31644, nodePort: 31644, protocol: UDP}
    - {name: rtp-31645, port: 31645, targetPort: 31645, nodePort: 31645, protocol: UDP}
    - {name: rtp-31646, port: 31646, targetPort: 31646, nodePort: 31646, protocol: UDP}
    - {name: rtp-31647, port: 31647, targetPort: 31647, nodePort: 31647, protocol: UDP}
    - {name: rtp-31648, port: 31648, targetPort: 31648, nodePort: 31648, protocol: UDP}
    - {name: rtp-31649, port: 31649, targetPort: 31649, nodePort: 31649, protocol: UDP}
    - {name: rtp-31650, port: 31650, targetPort: 31650, nodePort: 31650, protocol: UDP}
    - {name: rtp-31651, port: 31651, targetPort: 31651, nodePort: 31651, protocol: UDP}
    - {name: rtp-31652, port: 31652, targetPort: 31652, nodePort: 31652, protocol: UDP}
    - {name: rtp-31653, port: 31653, targetPort: 31653, nodePort: 31653, protocol: UDP}
    - {name: rtp-31654, port: 31654, targetPort: 31654, nodePort: 31654, protocol: UDP}
    - {name: rtp-31655, port: 31655, targetPort: 31655, nodePort: 31655, protocol: UDP}
    - {name: rtp-31656, port: 31656, targetPort: 31656, nodePort: 31656, protocol: UDP}
    - {name: rtp-31657, port: 31657, targetPort: 31657, nodePort: 31657, protocol: UDP}
    - {name: rtp-31658, port: 31658, targetPort: 31658, nodePort: 31658, protocol: UDP}
    - {name: rtp-31659, port: 31659, targetPort: 31659, nodePort: 31659, protocol: UDP}
