apiVersion: v1
kind: Service
metadata:
  name: dialer-rtp-32360-32379
  labels:
    app.kubernetes.io/name: dialer-engine
    app.kubernetes.io/component: rtp
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: dialer-engine
  ports:
    - {name: rtp-32360, port: 32360, targetPort: 32360, nodePort: 32360, protocol: UDP}
    - {name: rtp-32361, port: 32361, targetPort: 32361, nodePort: 32361, protocol: UDP}
    - {name: rtp-32362, port: 32362, targetPort: 32362, nodePort: 32362, protocol: UDP}
    - {name: rtp-32363, port: 32363, targetPort: 32363, nodePort: 32363, protocol: UDP}
    - {name: rtp-32364, port: 32364, targetPort: 32364, nodePort: 32364, protocol: UDP}
    - {name: rtp-32365, port: 32365, targetPort: 32365, nodePort: 32365, protocol: UDP}
    - {name: rtp-32366, port: 32366, targetPort: 32366, nodePort: 32366, protocol: UDP}
    - {name: rtp-32367, port: 32367, targetPort: 32367, nodePort: 32367, protocol: UDP}
    - {name: rtp-32368, port: 32368, targetPort: 32368, nodePort: 32368, protocol: UDP}
    - {name: rtp-32369, port: 32369, targetPort: 32369, nodePort: 32369, protocol: UDP}
    - {name: rtp-32370, port: 32370, targetPort: 32370, nodePort: 32370, protocol: UDP}
    - {name: rtp-32371, port: 32371, targetPort: 32371, nodePort: 32371, protocol: UDP}
    - {name: rtp-32372, port: 32372, targetPort: 32372, nodePort: 32372, protocol: UDP}
    - {name: rtp-32373, port: 32373, targetPort: 32373, nodePort: 32373, protocol: UDP}
    - {name: rtp-32374, port: 32374, targetPort: 32374, nodePort: 32374, protocol: UDP}
    - {name: rtp-32375, port: 32375, targetPort: 32375, nodePort: 32375, protocol: UDP}
    - {name: rtp-32376, port: 32376, targetPort: 32376, nodePort: 32376, protocol: UDP}
    - {name: rtp-32377, port: 32377, targetPort: 32377, nodePort: 32377, protocol: UDP}
    - {name: rtp-32378, port: 32378, targetPort: 32378, nodePort: 32378, protocol: UDP}
    - {name: rtp-32379, port: 32379, targetPort: 32379, nodePort: 32379, protocol: UDP}
