apiVersion: v1
kind: Service
metadata:
  name: dialer-rtp-31660-31679
  labels:
    app.kubernetes.io/name: dialer-engine
    app.kubernetes.io/component: rtp
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: dialer-engine
  ports:
    - {name: rtp-31660, port: 31660, targetPort: 31660, nodePort: 31660, protocol: UDP}
    - {name: rtp-31661, port: 31661, targetPort: 31661, nodePort: 31661, protocol: UDP}
    - {name: rtp-31662, port: 31662, targetPort: 31662, nodePort: 31662, protocol: UDP}
    - {name: rtp-31663, port: 31663, targetPort: 31663, nodePort: 31663, protocol: UDP}
    - {name: rtp-31664, port: 31664, targetPort: 31664, nodePort: 31664, protocol: UDP}
    - {name: rtp-31665, port: 31665, targetPort: 31665, nodePort: 31665, protocol: UDP}
    - {name: rtp-31666, port: 31666, targetPort: 31666, nodePort: 31666, protocol: UDP}
    - {name: rtp-31667, port: 31667, targetPort: 31667, nodePort: 31667, protocol: UDP}
    - {name: rtp-31668, port: 31668, targetPort: 31668, nodePort: 31668, protocol: UDP}
    - {name: rtp-31669, port: 31669, targetPort: 31669, nodePort: 31669, protocol: UDP}
    - {name: rtp-31670, port: 31670, targetPort: 31670, nodePort: 31670, protocol: UDP}
    - {name: rtp-31671, port: 31671, targetPort: 31671, nodePort: 31671, protocol: UDP}
    - {name: rtp-31672, port: 31672, targetPort: 31672, nodePort: 31672, protocol: UDP}
    - {name: rtp-31673, port: 31673, targetPort: 31673, nodePort: 31673, protocol: UDP}
    - {name: rtp-31674, port: 31674, targetPort: 31674, nodePort: 31674, protocol: UDP}
    - {name: rtp-31675, port: 31675, targetPort: 31675, nodePort: 31675, protocol: UDP}
    - {name: rtp-31676, port: 31676, targetPort: 31676, nodePort: 31676, protocol: UDP}
    - {name: rtp-31677, port: 31677, targetPort: 31677, nodePort: 31677, protocol: UDP}
    - {name: rtp-31678, port: 31678, targetPort: 31678, nodePort: 31678, protocol: UDP}
    - {name: rtp-31679, port: 31679, targetPort: 31679, nodePort: 31679, protocol: UDP}
