apiVersion: v1
kind: Service
metadata:
  name: dialer-metrics
  labels:
    app.kubernetes.io/name: dialer-engine
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dialer-engine
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
