apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backups
  labels:
    app.kubernetes.io/name: dialer-postgres
    app.kubernetes.io/component: backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
