apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dialer
  labels:
    app.kubernetes.io/name: dialer-engine
    app.kubernetes.io/component: api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 22m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dialer.playground.obvious.tech
      secretName: dialer-playground-tls
  rules:
    - host: dialer.playground.obvious.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dialer-api
                port:
                  number: 8080
