apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dialer-media
  labels:
    app.kubernetes.io/name: dialer-engine
    app.kubernetes.io/component: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
