apiVersion: v1
kind: Service
metadata:
  name: dialer-rtp-31520-31539
  labels:
    app.kubernetes.io/name: dialer-engine
    app.kubernetes.io/component: rtp
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: dialer-engine
  ports:
    - {name: rtp-31520, port: 31520, targetPort: 31520, nodePort: 31520, protocol: UDP}
    - {name: rtp-31521, port: 31521, targetPort: 31521, nodePort: 31521, protocol: UDP}
    - {name: rtp-31522, port: 31522, targetPort: 31522, nodePort: 31522, protocol: UDP}
    - {name: rtp-31523, port: 31523, targetPort: 31523, nodePort: 31523, protocol: UDP}
    - {name: rtp-31524, port: 31524, targetPort: 31524, nodePort: 31524, protocol: UDP}
    - {name: rtp-31525, port: 31525, targetPort: 31525, nodePort: 31525, protocol: UDP}
    - {name: rtp-31526, port: 31526, targetPort: 31526, nodePort: 31526, protocol: UDP}
    - {name: rtp-31527, port: 31527, targetPort: 31527, nodePort: 31527, protocol: UDP}
    - {name: rtp-31528, port: 31528, targetPort: 31528, nodePort: 31528, protocol: UDP}
    - {name: rtp-31529, port: 31529, targetPort: 31529, nodePort: 31529, protocol: UDP}
    - {name: rtp-31530, port: 31530, targetPort: 31530, nodePort: 31530, protocol: UDP}
    - {name: rtp-31531, port: 31531, targetPort: 31531, nodePort: 31531, protocol: UDP}
    - {name: rtp-31532, port: 31532, targetPort: 31532, nodePort: 31532, protocol: UDP}
    - {name: rtp-31533, port: 31533, targetPort: 31533, nodePort: 31533, protocol: UDP}
    - {name: rtp-31534, port: 31534, targetPort: 31534, nodePort: 31534, protocol: UDP}
    - {name: rtp-31535, port: 31535, targetPort: 31535, nodePort: 31535, protocol: UDP}
    - {name: rtp-31536, port: 31536, targetPort: 31536, nodePort: 31536, protocol: UDP}
    - {name: rtp-31537, port: 31537, targetPort: 31537, nodePort: 31537, protocol: UDP}
    - {name: rtp-31538, port: 31538, targetPort: 31538, nodePort: 31538, protocol: UDP}
    - {name: rtp-31539, port: 31539, targetPort: 31539, nodePort: 31539, protocol: UDP}
