apiVersion: v1
kind: Service
metadata:
  name: dialer-rtp-31540-31559
  labels:
    app.kubernetes.io/name: dialer-engine
    app.kubernetes.io/component: rtp
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: dialer-engine
  ports:
    - {name: rtp-31540, port: 31540, targetPort: 31540, nodePort: 31540, protocol: UDP}
    - {name: rtp-31541, port: 31541, targetPort: 31541, nodePort: 31541, protocol: UDP}
    - {name: rtp-31542, port: 31542, targetPort: 31542, nodePort: 31542, protocol: UDP}
    - {name: rtp-31543, port: 31543, targetPort: 31543, nodePort: 31543, protocol: UDP}
    - {name: rtp-31544, port: 31544, targetPort: 31544, nodePort: 31544, protocol: UDP}
    - {name: rtp-31545, port: 31545, targetPort: 31545, nodePort: 31545, protocol: UDP}
    - {name: rtp-31546, port: 31546, targetPort: 31546, nodePort: 31546, protocol: UDP}
    - {name: rtp-31547, port: 31547, targetPort: 31547, nodePort: 31547, protocol: UDP}
    - {name: rtp-31548, port: 31548, targetPort: 31548, nodePort: 31548, protocol: UDP}
    - {name: rtp-31549, port: 31549, targetPort: 31549, nodePort: 31549, protocol: UDP}
    - {name: rtp-31550, port: 31550, targetPort: 31550, nodePort: 31550, protocol: UDP}
    - {name: rtp-31551, port: 31551, targetPort: 31551, nodePort: 31551, protocol: UDP}
    - {name: rtp-31552, port: 31552, targetPort: 31552, nodePort: 31552, protocol: UDP}
    - {name: rtp-31553, port: 31553, targetPort: 31553, nodePort: 31553, protocol: UDP}
    - {name: rtp-31554, port: 31554, targetPort: 31554, nodePort: 31554, protocol: UDP}
    - {name: rtp-31555, port: 31555, targetPort: 31555, nodePort: 31555, protocol: UDP}
    - {name: rtp-31556, port: 31556, targetPort: 31556, nodePort: 31556, protocol: UDP}
    - {name: rtp-31557, port: 31557, targetPort: 31557, nodePort: 31557, protocol: UDP}
    - {name: rtp-31558, port: 31558, targetPort: 31558, nodePort: 31558, protocol: UDP}
    - {name: rtp-31559, port: 31559, targetPort: 31559, nodePort: 31559, protocol: UDP}
