apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: voice-dialer
resources:
  - volume-snapshot.yaml
  - snapshot-restore-pvc.yaml
  - logical-restore-job.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: voice-dialer
